spring.application.name=Tienda TCG

spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_tcg
spring.datasource.username=tienda_tcg_app
spring.datasource.password=${TIENDA_TCG_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}

pokemon.tcg.base-url=https://api.pokemontcg.io/v2